### ISSUE TITLE
Query URL is incorrect for TQL

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#15]
The language for the valueset query extension is wrong on this valueset:

http://build.fhir.org/ig/cqframework/opioid-cds/ValueSet-illicit-drug-urine-screening.xml.html

Should be TQL http://www.apelondts.org/tql

**Comment by sliver007** [comment]
This issue seems to have been resolved. Looking at the ValueSet mentioned in this issue and all other ValueSet files that contain "apelon" and they all have the correct/specified URL (http://www.apelondts.org/tql).

**Comment by c-schuler** [comment]
It looks like this issue was resolved in the following commit by the reporter: https://github.com/cqframework/opioid-cds/commit/d70614889682d2a234bad9ee6633fbdf51c34343#diff-e7e889bbd1827c35928adce02eff039f. Closing.
