### ISSUE TITLE
Magic Numbers in Recommendation #7

### ISSUE THREAD

**Issue by gtoups** [cqframework/opioid-cds#21]
Page: http://build.fhir.org/ig/cqframework/opioid-cds/recommendation-07.html

There are several numbers or ranges in the logic description that aren’t easily found in the
recommendation statement.

How were these ranges determined? How should the information be conveyed to the reader?

**Comment by sliver007** [comment]
Clarification Bryn received from "The Team":

"Here's the response from the project team. So I'd suggest documentation along the lines of:

The ranges introduced are based on practical considerations for identifying a course of treatment likely to be subject to the recommendation. They were arrived at through discussion with pilot partner clinicians."

**Comment by JPercival** [comment]
Resolved by #47
