### ISSUE TITLE
OMTK Libraries: v0.0.1 vs v0.1.0

### ISSUE THREAD

**Issue by gtoups** [cqframework/opioid-cds#23]
Based on feedback from MITRE (see [MIH-47](https://jira.harmoniqhealth.com/browse/MIH-47)) on all Recommendation Pages: 

> Two versions of the OMTK library are listed and it’s not clear what the differences are until the
> implementor reads the individual files. At the least, it would be helpful to clearly indicate the
> difference in the descriptions that show up in the Content listings. Given that the difference
> between the files is how they get data (data source vs library w/ static data), and that they
> actually represent two different use cases / implementation options, it seems they should
> actually be two different libraries rather than two versions of the same library.

**Comment by JPercival** [comment]
It looks to me that it's possible this doesn't represent two different libraries, but that the older library just used static data as a placeholder. It also doesn't appears that the recommendation cql uses the updated library. @c-schuler what's your take?

**Comment by sliver007** [comment]
Agree that we should update the name, but will do that as a separate story as part of vNext. For this issue, update the documentation to describe the differences in the current libraries.

**Comment by brynrhodes** [comment]
Addressed as part of v1.1.0
