### ISSUE TITLE
Canonical URLs resulting in broken links

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#26]
The broken links can be found in the "url" element in the Library, PlanDefinition, and ValueSet resources. For example: http://build.fhir.org/ig/cqframework/opioid-cds/Library-opioidcds-recommendation-04.html

**Comment by brynrhodes** [comment]
Verified the URL element in the above link (and throughout the IG) is correct. As with all conformance resources, the URL is not necessarily expected to resolve (it's really a URI at this point), but the goal is that in the published content, the URL would resolve, so it's still called a URL.
