### ISSUE TITLE
Use of Coding[0]

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#27]
There are several places in the CQL where only the first code in a concept is tested for inclusion. This needs to be altered to check each code in the concept for inclusion.

**Comment by JPercival** [comment]
Still present in a number of files, for example:

https://github.com/cqframework/opioid-cds/blob/master/pages/cql/OpioidCQM_STU3-0.1.0.cql

**Comment by brynrhodes** [comment]
Post v1.1.0, still present in the Prescriptions function, but that usage is 1) commented, and 2) symptomatic of a larger issue with medication being modeled as a "CodeableReference" that we need to address another way. Therefore, closing this as addressed by v1.1.0
