### ISSUE TITLE
GetDurationInDays Incorrectly Calculates on Some Units

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#29]
Found in the [Common library](https://github.com/cqframework/opioid-cds/blob/61dcf68e6166232fadd0564f7b5f4d0a3bbb68f8/pages/cql/OpioidCDS_STU3_Common.cql).
MedicationOrder.dispenseRequest.expectedSupplyDuration does not constrain units on duration, so it can be any of the valid UCUM duration units. The GetDurationInDays function only addresses a (year) and mo (month) and defaults all others to days. This means a duration expressed in weeks, hours, minutes, seconds, or ms would be calculated incorrectly. Even if those units aren’t likely, it’s safest to either support these units or specifically handle ‘d’ and error out (or null out) on any unsupported units. That said, it seems that a medication supply expressed in weeks could happen.

**Comment by JPercival** [comment]
Resolved by #47
