### ISSUE TITLE
Display message for recommendation #4 should use medication name

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#3]
The message produced by this expression will be displayed to a user, so it should use a user-friendly description, the medication name at least, rather than the id:

https://github.com/cqframework/opioid-cds/blob/e2714e8093dc340e9e9b69a240e2355b6da888b6/pages/cql/OpioidCDS_STU3_REC_04.cql#L79

**Comment by JPercival** [comment]
Already fixed in master
