### ISSUE TITLE
“Get Detail” Concatenates String and List of Strings and Might Throw a Run-Time Error

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#31]
Found in [recommendation #4 CQL](https://github.com/cqframework/opioid-cds/blob/61dcf68e6166232fadd0564f7b5f4d0a3bbb68f8/pages/cql/OpioidCDS_STU3_REC_04.cql)

```
define "Get Detail":
  'The following medication requests(s) release rates should be re-evaluated: ' + Common.GetMedicationNames("Trigger Event Prescriptions")
```

This isn’t valid as-is, but CQL-to-ELM tries to be smart, so it applies a SingletonFrom to the list (actually, it applies it twice for some reason). The problem is, this means that if multiple prescriptions are passed in, this CQL will throw a run-time error (per spec).

This code should be using the String Combine operator (with a comma separator) on the list before concatenating.

**Comment by JPercival** [comment]
Resolved by #47
