### ISSUE TITLE
Unnecessary Intersection

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#32]
Found in [guideline 10 CQL](https://github.com/cqframework/opioid-cds/blob/61dcf68e6166232fadd0564f7b5f4d0a3bbb68f8/pages/cql/OpioidCDS_STU3_REC_10.cql)

The intersection in the CQL below seems unnecessary. “A except (A intersect B)” is logically equivalent to “A except B”.

```
define "Unprescribed Opioids":
  "Opioids From Most Recent Screening" except
    ("Opioids From Most Recent Screening" intersect "Prescribed Opioids")
```

**Comment by JPercival** [comment]
Resolved by #48
