### ISSUE TITLE
Missing Opioids

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#33]
Found in [guideline 10 CQL](https://github.com/cqframework/opioid-cds/blob/61dcf68e6166232fadd0564f7b5f4d0a3bbb68f8/pages/cql/OpioidCDS_STU3_REC_10.cql)

The CQL for “Missing Opioids” seems a bit fragile in that it relies on specific display names of urine drug tests and how they match up to specific ingredient names from the prescription drugs. This may be the best approach (as it’s a tough problem), but it probably deserves some commentary in the code and/or documentation so implementors understand that tight dependency between the medication code displays and urine drug screen code displays.

**Comment by JPercival** [comment]
Resolved by #48
