### ISSUE TITLE
GetDrug Function

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#34]
Found in [guideline 10 CQL](https://github.com/cqframework/opioid-cds/blob/61dcf68e6166232fadd0564f7b5f4d0a3bbb68f8/pages/cql/OpioidCDS_STU3_REC_10.cql)

The GetDrug function could use some documentation indicating the approach it takes to extracting the drug name. It may also benefit from a more specific name (e.g., “GetDrugNameFromScreeningCode”). Lastly, there are some codes in the screening value set that have the form “DrugName cutoff ...” – those will never match an ingredient name. Should the GetDrug function also test for “cutoff” and truncate there?

**Comment by JPercival** [comment]
Resolved by #48
