### ISSUE TITLE
End of Life Assessment function is somewhat confusing

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#4]
Because the End of Life Assessment function takes the context prescriptions as a parameter, it implies that those are being used to make the determination. And while technically they are, they are only a small part of what the function is really doing, and most of that has nothing to do with the context prescriptions.

I suggest making End of Life Assessment an expression definition that includes everything but the context prescription check, and create a different function for that aspect that takes the prescriptions as a parameter, perhaps "Prescriptions for End of Life Medication".

https://github.com/cqframework/opioid-cds/blob/e2714e8093dc340e9e9b69a240e2355b6da888b6/pages/cql/OpioidCDS_STU3_Common.cql#L47

**Comment by JPercival** [comment]
Already fixed in master
