### ISSUE TITLE
Remove Get from function names

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#5]
This is a nitpick for sure, but the use of "Get" in the function names is a bit distracting. Suggest removing the "Get" from the names here.

https://github.com/cqframework/opioid-cds/blob/e2714e8093dc340e9e9b69a240e2355b6da888b6/pages/cql/OpioidCDS_STU3_Common.cql#L38

**Comment by JPercival** [comment]
Already fixed in master
