### ISSUE TITLE
Refresh Value Sets

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#58]
Value Set Scope (from the VSD) is intended to be always and forever a narrative description (not coded) consisting of the Description of the value set, the Clinical Focus, and the Inclusion/Exclusion narrative. We put those elements into description, useContext[clinical-focus] and inclusion and exclusion extensions. For this refresh, the narrative should all be put into description and not usageContext, inclusion, and exclusion.

Purpose will be used to capture the reason the value set was created.

Terminology updates will be provided that we reimport from, and the updates will provide explicit content for each of these elements.

**Comment by brynrhodes** [comment]
Updated terminology is available here:
https://docs.google.com/spreadsheets/d/1oU-LbcrOJUfOU4PjQp6yaHRWOQeRvjSDuxhsTvC8bLs/edit#gid=0

Note that this must be implemented according to the guidance for the use of terminology here:
http://build.fhir.org/ig/HL7/cqf-recommendations/documentation-terminology.html

Specifically, the valuesets in that spreadsheet should all be generated using the terminology template data provided. Each one will produce two value set resources, one a cpg-expressionbasedvalueset that defines the value set as a compose, rules-text, or expression, and two, a cpg-cachedvalueset that provides an enumerated compose definition of the value set contents (from the -cl (codelist)) sheets.

**Comment by sliver007** [comment]
Value sets have all been refresh and in use for some time. Reviewed the resources and it seems like these recommendations were done as part of that refresh.
