### ISSUE TITLE
Duration and Period must use UCUM units

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#6]
FHIR Duration and Period units be specified with UCUM. Period.unit has a required binding to [UnitsOfTime](http://hl7.org/fhir/valueset-units-of-time.html).

https://github.com/cqframework/opioid-cds/blob/e2714e8093dc340e9e9b69a240e2355b6da888b6/pages/cql/OpioidCDS_STU3_Common.cql#L205

**Comment by JPercival** [comment]
Already fixed in master
