### ISSUE TITLE
Why declare functions for these?

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#7]
What is the value of having these defined as functions? Why not just reference the value sets from the source? Using functions obscures that all we are doing is a value set membership test:

https://github.com/cqframework/opioid-cds/blob/e2714e8093dc340e9e9b69a240e2355b6da888b6/pages/cql/OpioidCDS_STU3_Common.cql#L232

**Comment by JPercival** [comment]
Already in master
