### ISSUE TITLE
OMTKLogic Library Rename

### ISSUE THREAD

**Issue by sliver007** [cqframework/opioid-cds#77]
Based on feedback from MITRE (see MIH-47) on all Recommendation Pages: 

> Two versions of the OMTK library are listed and it’s not clear what the differences are until the
implementor reads the individual files. At the least, it would be helpful to clearly indicate the
difference in the descriptions that show up in the Content listings. Given that the difference
between the files is how they get data (data source vs library w/ static data), and that they
actually represent two different use cases / implementation options, it seems they should
actually be two different libraries rather than two versions of the same library.

Rename OMTKLogic-0.1.0 to OMTKLogicWithData and OMTKLogic-0.0.1 to OMTKLogicWithCQL

**Comment by brynrhodes** [comment]
Addressed as part of v1.1.0
