### ISSUE TITLE
Define a code for 'POS'

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/opioid-cds#8]
Is the 'POS' here a code from a known terminology? We should at the very least define a code and use that for the reference, a binding in a profile would be good as well.

https://github.com/cqframework/opioid-cds/blob/e2714e8093dc340e9e9b69a240e2355b6da888b6/pages/cql/OpioidCDS_STU3_REC_10.cql#L86

**Comment by JPercival** [comment]
Already in master
