### ISSUE TITLE
Discrepancies in logic with what is provided by Us Core

### ISSUE THREAD

**Issue by c-schuler** [cqframework/opioid-cds#87]
Us Core provides MedicationRequest.medication as a Reference --> Logic assumes a CodeableConcept

Us Core defines ambulatory prescriptions by setting the MedicationRequest.category to "Community" --> Logic assumes "Outpatient"

Us Core does not provide an interpretation for drug screening observations --> Logic assumes an interpretation code of "POS" to be provided

The resolution of this task requires refactoring the logic to use Us Core's modeling.

**Comment by brynrhodes** [comment]
Addressed by v1.1.0
