### ISSUE TITLE
Common - Switch 'Outpatient' and 'Referral to Hospice' codes to use value sets

### ISSUE THREAD

**Issue by sliver007** [cqframework/opioid-cds#90]
In the Opioid_STU3_Common library, the 'Outpatient' and 'Referral to Hospice' codes should be switched to value sets and the dependent queries/retrieves modified accordingly. 

'Outpatient' -> valueset "Outpatient": 'http://hl7.org/fhir/ValueSet/medication-request-category'
'Referral to Hospice' -> valueset "Referral to Hospice": 'http://fhir.org/guides/cdc/opioid-cds/ValueSet/substance-abuse'

**Comment by brynrhodes** [comment]
Overtaken by v1.1.0
